config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: "homes#top"

	resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
	resources :users, only: [:show, :edit, :index, :update]



	get 'homes/about' => 'homes#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	has_one_attached :image
	belongs_to :user
	
	validates :title, presence: true
  validates :body, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]






  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :is_matching_login_user, only: [:edit, :update]


    # 投稿データの保存
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    @user = @book.user

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to books_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end


  def edit
    @book = Book.find(params[:id])
  end

  def index
    @book = Book.new
    @books = Book.all
    @user =  User.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
    redirect_to book_path(book.id)
    else
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to books_path
  end

  # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def top
		
	end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @new_book = Book.new
    @users = User.all
    @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<!-- ユーザーの詳細 -->
<div>
  <h1>User info</h1>
  <%= image_tag user.get_profile_image(100,100) %></p>

</div>

<table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</tbody></table>

<% if user == current_user %>
    <p><%= link_to "プロフィール設定", edit_user_path(user) %></p>
  <% end %>

<h1>New book</h1>
<%= form_with model: new_book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h2>Editing Book</h2>
  <%= form_with model: @book do |f| %>
  <label for="inputTitle">Title</label>
  <%= f.text_field :title, autofocus: true, id:"inputTitle" %>
  <label for="inputOpinion">Opinion</label>
  <%= f.text_area :body, autofocus: true, id:"inputOpinion" %>
  <%= f.submit "Update Book" %>

  <%= link_to "Show", book_path(@book.id) %>
  <%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<%= render 'book', user: @user, new_book: @new_book %>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<% @books.each do |book| %>
  <div>
  <%= link_to book_path(book.id) do %>
   Title：<%= book.title %>
  <% end %>
  <%= image_tag book.get_image %>
  <p>Opinion：<%= book.body %></p>
  </div>
<% end %>

app/views/books/show.html.erb
<h1>Book detail</h1>

<div>
  <%= link_to user_path(@book.user_id) do %>
    <%= image_tag @user.get_profile_image(100,100) %></p>
  <% end %>
  <%= link_to @book.user.name, user_path(@book.user_id) %>
  <%= link_to @book.title, book_path(@book.id) %></p>
  <p><%=@book .body %></p>
  <% if @book.user == current_user %>
    <%= link_to "Edit", edit_book_path(@book.id) %>
    <%= link_to "Destroy", book_path(@book), method: :delete %>
  <% end %>
</div>

app/views/homes/about.html.erb
<body>
    <main>
        <p id = "notice"></p>
        <div class = "row">
            <h1 class = "px-3 mx-auto">
                Welcome to
                <i class="fa-solid fa-book"></i>
                <strong>Bookers</strong>
                !
            </h1>
        </div>
    </main>
</body>

app/views/homes/top.html.erb
<main>
  <div class = "container">
    <div class = "mx-auto col-11 col-sm col-lg-8 col-xl-6">
      <h1>
        welcome to
        <i class="fa-solid fa-book"></i>
        <strong>Bookers</strong>
        !!
      </h1>
      <p>
        In
        <i class="fa-solid fa-book"></i>
        <strong>Bookers</strong>
        ,
      </p>
      <p>
        you can share and exchange your opinions , inpressions , and emotions<br>
        about various books!
      </p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/b064cb6ea9.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
    <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
      <div class = "container">
        <a class = "navbar-brand" href = >
          <span>Bookers</span>
        </a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class = "navbar-collapse collapse" id = "navbarNavDropdown" style>
        <ul class = "navbar-nav ml-auto">
          <li>
          <a class = "nav-link text-light" href = ""></a>
        </ul>
      </div>

    <% if user_signed_in? %>

      <li>
        <%= link_to user_path(current_user.id) do %>
          <i class="fa-solid fa-house"></i>
        <% end %>
        <%= link_to 'Home', user_path(current_user.id) %>    </li>

      <li>
        <%= link_to users_path do %>
          <i class="fa-solid fa-users"></i>
        <% end %>
        <%= link_to 'Users', users_path %>    </li>

      <li>
        <%= link_to books_path do %>
          <i class="fa-solid fa-book-open"></i>
        <% end %>
        <%= link_to "Books", books_path %>
      </li>
      <li>
        <%= link_to destroy_user_session_path do %>
          <i class="fa-solid fa-right-from-bracket"></i>
        <% end %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>

       <li>
        <%= link_to root_path do %>
          <i class="fa-solid fa-house"></i>
        <% end %>
         <%= link_to "Home", root_path %>
       </li>
       <li>
        <%= link_to homes_about_path do %>
          <i class="fa-solid fa-link"></i>
        <% end %>
        <%= link_to "About", homes_about_path %>
      </li>
      <li>
         <%= link_to new_user_registration_path do %>
          <i class="fa-solid fa-user-plus"></i>
        <% end %>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to new_user_session_path do %>
          <i class="fa-solid fa-right-to-bracket"></i>
        <% end %>
        <%= link_to "Log in", new_user_session_path %>
      </li>
    <% end %>
         </div>
    </nav>
  </header>

   <div class="body">
      <p class="notice"><%= notice %></p>

      <%= yield %>
  <footer>
    <div class="container mt-5">
  	  <div class="row">
    	  <div class="mx-auto">
    		  <p>CopyRight Infratop.inc</p>
    	  </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/_user.html.erb
<!-- ユーザーの詳細 -->
<div>
  <h1>User info</h1>
  <%= image_tag user.get_profile_image(100,100) %></p>

</div>

<table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</tbody></table>

<% if user == current_user %>
    <p><%= link_to "プロフィール設定", edit_user_path(user) %></p>
  <% end %>

<h1>New book</h1>
<%= form_with model: new_book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<%= render 'user', user: @user, new_book: @new_book %>


<% @users.each do |user| %>
    <%= image_tag user.get_profile_image(100,100)  %>
    <%= user.name %>
    <%= link_to 'Show', user %>



<% end %>

app/views/users/show.html.erb
<%= render 'user', user: @user, new_book: @new_book %>

<!-- ユーザーの投稿一覧 -->

<% @books.each do |book| %>
<div>
  <%= link_to user_path(book.user_id) do %>
    <%= image_tag book.get_image %>
  <% end %>
<%= link_to book_path(book.id) do %>
<%= book.title %>
<% end %>
<%= book.body %>
</div>
<% end %>